### ISSUE TITLE
Py23DocChecker makes test always pass on Python 2

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.customerize#18]
The `Py23DocChecker` doctest compatibility class has a typo which basically sets [`got = want`](https://github.com/plone/plone.app.customerize/blob/1.3.9/plone/app/customerize/tests/testDocTests.py#L17) which means the doctests always pass on Python 2.

This is the same as for https://github.com/plone/plone.indexer/issues/7.
I originally found and fixed this in [plone.formwidget.namedfile](https://github.com/plone/plone.formwidget.namedfile/pull/38/commits/39755889acf85442854b97ec5a5de88a84d3b7e5#diff-7460ef32fb7a01f83c6d3a7c91c226c6L15)
If I have searched correctly, these three packages are the only ones with this problem

**Comment by mauritsvanrees** [comment]
For the record, after disabling the `got = want` line, these are the failures:

```
Failure in test /Users/maurits/community/plone-coredev/5.2/src/plone.app.customerize/plone/app/customerize/tests/testBrowserLayers.txt
Failed doctest test for testBrowserLayers.txt
  File "/Users/maurits/community/plone-coredev/5.2/src/plone.app.customerize/plone/app/customerize/tests/testBrowserLayers.txt", line 0

----------------------------------------------------------------------
File "/Users/maurits/community/plone-coredev/5.2/src/plone.app.customerize/plone/app/customerize/tests/testBrowserLayers.txt", line 12, in testBrowserLayers.txt
Failed example:
    print('Should give doctest failure')
Expected:
    Nah!
Got:
    Should give doctest failure
----------------------------------------------------------------------
File "/Users/maurits/community/plone-coredev/5.2/src/plone.app.customerize/plone/app/customerize/tests/testBrowserLayers.txt", line 25, in testBrowserLayers.txt
Failed example:
    browser.open('http://nohost/plone/@@layer-test-view')
Expected:
    Traceback (most recent call last):
    ...
    zExceptions.NotFound: ...
Got:
    Traceback (most recent call last):
      File "/usr/local/py27/parts/opt/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest testBrowserLayers.txt[11]>", line 1, in <module>
        browser.open('http://nohost/plone/@@layer-test-view')
      File "/Users/maurits/shared-eggs/cp27m/zope.testbrowser-5.3.2-py2.7.egg/zope/testbrowser/browser.py", line 251, in open
        self._processRequest(url, make_request)
      File "/Users/maurits/shared-eggs/cp27m/zope.testbrowser-5.3.2-py2.7.egg/zope/testbrowser/browser.py", line 275, in _processRequest
        resp = make_request(reqargs)
      File "/Users/maurits/shared-eggs/cp27m/zope.testbrowser-5.3.2-py2.7.egg/zope/testbrowser/browser.py", line 249, in make_request
        return self.testapp.get(url, **args)
      File "/Users/maurits/shared-eggs/cp27m/WebTest-2.0.33-py2.7.egg/webtest/app.py", line 335, in get
        expect_errors=expect_errors)
      File "/Users/maurits/shared-eggs/cp27m/zope.testbrowser-5.3.2-py2.7.egg/zope/testbrowser/browser.py", line 94, in do_request
        expect_errors)
      File "/Users/maurits/shared-eggs/cp27m/WebTest-2.0.33-py2.7.egg/webtest/app.py", line 628, in do_request
        res = req.get_response(app, catch_exc_info=True)
      File "/Users/maurits/shared-eggs/cp27m/WebOb-1.8.5-py2.7.egg/webob/request.py", line 1310, in send
        application, catch_exc_info=True)
      File "/Users/maurits/shared-eggs/cp27m/WebOb-1.8.5-py2.7.egg/webob/request.py", line 1278, in call_application
        app_iter = application(self.environ, start_response)
      File "/Users/maurits/shared-eggs/cp27m/WebTest-2.0.33-py2.7.egg/webtest/lint.py", line 201, in lint_app
        iterator = application(environ, start_response_wrapper)
      File "/Users/maurits/shared-eggs/cp27m/plone.testing-7.0.1-py2.7.egg/plone/testing/_z2_testbrowser.py", line 38, in wrapped_func
        return func(*args, **kw)
      File "/Users/maurits/shared-eggs/cp27m/plone.testing-7.0.1-py2.7.egg/plone/testing/_z2_testbrowser.py", line 65, in __call__
        wsgi_result = publish(environ, start_response)
      File "/Users/maurits/shared-eggs/cp27m/Zope-4.0b10-py2.7.egg/ZPublisher/WSGIPublisher.py", line 295, in publish_module
        response = _publish(request, new_mod_info)
      File "/Users/maurits/shared-eggs/cp27m/Zope-4.0b10-py2.7.egg/ZPublisher/WSGIPublisher.py", line 217, in publish
        obj = request.traverse(path, validated_hook=validate_user)
      File "/Users/maurits/shared-eggs/cp27m/Zope-4.0b10-py2.7.egg/ZPublisher/BaseRequest.py", line 536, in traverse
        return response.notFoundError(URL)
      File "/Users/maurits/shared-eggs/cp27m/Zope-4.0b10-py2.7.egg/ZPublisher/HTTPResponse.py", line 975, in notFoundError
        raise exc
    NotFound: http://nohost/plone/@@layer-test-view
----------------------------------------------------------------------
File "/Users/maurits/community/plone-coredev/5.2/src/plone.app.customerize/plone/app/customerize/tests/testBrowserLayers.txt", line 236, in testBrowserLayers.txt
Failed example:
    sorted(list(with_layer.difference(without_layer)))
Expected:
    ['layer-test-view', 'layer-test-viewlet']
Got:
    ['layer-test-view', u'layer-test-viewlet']

                
  Ran 2 tests with 2 failures, 0 errors, 0 skipped in 5.051 seconds.
```

**Comment by gforcada** [comment]
@mauritsvanrees did you grep through all the modules to see if this is happening on more packages as well? :thinking: 

Great finding! :+1:

**Comment by mauritsvanrees** [comment]
Yes, as the main issue text says: "If I have searched correctly, these three packages are the only ones with this problem." :-)

**Comment by gforcada** [comment]
:sweat_smile: sorry it was too late and I did not read :sleepy:
